TELEGRAM_TOKEN = "7046029904:AAGjnuy_nDLObNB3iVHUkXzo3AiTWxqOEgo"
WEBHOOK_URL ="https://t.me/Pothuraju_bot"
DATABASE_URL = "postgres://chatbotug_db_user:BxOeQ7ccCNKsyA0Q6WEUXg3IUREGUJnb@dpg-cm3svhmn7f5s73br808g-a.oregon-postgres.render.com/chatbotug_db"
EMAIL_SENDER = "josefelipeguillenmiraba@gmail.com"
EMAIL_PASSWORD = "qgezogbyxzkugfbm"